services:
  frontend:
    image: kkrishnateja05/money-tracker-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: kkrishnateja05/money-tracker-backend:latest
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/transactionDB
    depends_on:
      - mongo

  mongo:
    image: kkrishnateja05/money-tracker-mongo:latest
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
