version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/transactionDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
